### ISSUE TITLE
SDK Bug

### ISSUE THREAD

**Issue by vinoo999** [USDepartmentofLabor/PHP_DOLDataSDK#2]
In order to access data hosted at https://data.dol.gov there is no option in the SDK that handles this.
It could be that the API V2 database is not actually stored at http://quarry.dol.gov (which in fact redirects as a nonexistent page) but instead at the aforementioned address. 

I replaced all http://quarry.dol.gov with https://data.dol.gov and I can now access the datasets on the data.dol.gov RESTful interface.

**Comment by joey-spooner** [comment]
Thank you, @vinoo999. We'll get this updated tomorrow. Nice catch!

**Comment by joey-spooner** [comment]
@vinoo999 I think we've got it fixed, please confirm when you have a moment. Thanks!

**Comment by vinoo999** [comment]
Not sure if it is working for you but only works for me when it is http**s**://data.dol.gov  as opposed to http://data.dol.gov  
Otherwise that's it. Thanks for the fast fix.

**Comment by joey-spooner** [comment]
Thanks for pointing that out @vinoo999. We'll get that fixed in a future release. I'll reach out to you when it's done.

**Comment by vinoo999** [comment]
@spoonstein  Do you know if something changed in the API dramatically other than the offset feature for the Quarry API? I returned to this project I was working on and suspiciously my entire account along with my API Keys were deleted and queries no longer seem to be working with the API... Using the updated functioning SDK from before (specifically V2) I tried just getting the top 200 results from /get/inspection (that is _$method = 'get';_ and _$arguments = Array('table_alias' = 'inspection');_

Calling the API returns an empty array... Just wondering why this may have happened. Thanks.

_EDIT_
Might be my bad or SDK bug. Just executed a curl request for the same manually and it worked so not an API issue. Sorry.

**Comment by joey-spooner** [comment]
No worries @vinoo999. So your calls are working now? 

Anything else that's a concern/potential bug beyond the HTTPS previously mentioned?

**Comment by vinoo999** [comment]
@spoonstein My curl calls from terminal are working. Trying to test what is wrong with the request through the SDK. Could be something silly on my side but will take a look this evening or tomorrow morning and keep you posted.

One other slight bug I actually noticed while trying to debug was that with the old api (at api.dol.gov) in the SDK nothing ever sets apiURL to V1 (only necessary because the way it is added to the curl URL is through apiURL). Several options to fix:  I was lazy and just added the below in the updateContext() function already being called in the construct.

``` php
if ($this->apiHost == "http://api.dol.gov"){
            $this->apiURL = 'V1';
        }
```

**Comment by joey-spooner** [comment]
Thanks, @vinoo999. Please keep me posted. As for the potential SDK bug, the team will look into it tomorrow and may post a bug if they confirm one does exist beyond HTTPS.

**Comment by vinoo999** [comment]
No luck for me today, @spoonstein. 
Just for reference I can execute this in my Terminal which simply returns the first 10 items in the OSHA Inspection table with the columns activity_nr and estab_name.

``` bash
curl -H "X-API-KEY: MY_API_KEY" https://data.dol.gov/get/inspection/format/json/limit/10/columns/{activity_nr:estab_name}
```

Trying the same using the SDK returns nothing (an empty array as casted in the SDK but no error)

``` php
$context = new GOVDataContext('https://data.dol.gov', MY_API_KEY, null);
$request = new GOVDataRequest($context);
$method = 'get';
$arguments =  Array('table_alias' => 'inspection', 
                        'format' => 'json',
                        'limit' => 10, 
                        'columns' => "{activity_nr:estab_name}");
$results = $request->callAPI($method, $arguments);
print_r($results);
```

**Comment by johnstorey** [comment]
@vinoo999 Any progress since last August? I've just started trying this today and am running into all kinds of issues, from TLS terminations with curl to failures as you described with PHP.

**Comment by vinoo999** [comment]
@johnstorey We actually abandoned (temporarily) using the API and just downloaded the raw data for our project, but I'll take another look this weekend and let you know. I think they updated the API in November with some more features which may have broke the SDK again.

**Comment by johnstorey** [comment]
Looking at  the Ruby API I see some differences. I'll see if I can't find anything there. If not we'll download the data raw ourselves.

Thanks for the reply!

**Comment by johnstorey** [comment]
@vinoo999 By the way, I'm assuming that by downloading the raw data you are using curl. Or have you found another way (curl is telling me that the server is terminating the connection before it completes, even with a 15 minute timeout.)

**Comment by vinoo999** [comment]
@johnstorey I didn't have to use curl at all (back in September-ish). They had massive csvs (or xml as you please) from [here](http://ogesdw.dol.gov/views/data_catalogs.php) but the requests from my browser time out too... Probably the same issue you're facing. The ogesdw.dol.gov host seems to be unresponsive. You could try [this](https://devtools.dol.gov/APISampler/Home/SearchIndex). Not sure what's in there but you could scrape the HTML from the queries if you need (maybe) because I think that is working...

**Comment by Supreet7** [comment]
Hi Can you  try this

1.	Go to https://github.com/USDepartmentofLabor/PHP_DOLDataSDK/tree/ps-2 and either GIT clone or download the zip repository.
2.	Open the folder PHP_DOLDataSK-ps-2 and edit “sample.php”
3.	To edit APIv1
a.	Comment out the APIv2-Quarry $context variable.
b.	Uncomment //APIv1 $context variable and replace ADD_YOUR_API_KEY_HERE with your apiv1 active key
c.	Enter your array arguments at line 27
d.	Save and run sample.php for the output
4.	To edit Quarry API
a.	Go to sample.php
b.	Comment out //APIv1 $context
c.	Uncomment //APIv2-Quarry $context variable
d.	Enter your Quarry arguments starting at line 37. 
e.	Save and run sample.php

**Comment by vinoo999** [comment]
I found a new site for raw data if you need it [here](https://enforcedata.dol.gov/views/data_catalogs.php).
